# Generated by Django 5.2.10 on 2026-01-08 19:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('wordpress_url', models.URLField(max_length=500)),
                ('license_key', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('text_model', models.CharField(blank=True, max_length=100, null=True)),
                ('image_model', models.CharField(blank=True, max_length=100, null=True)),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('technical', 'Technical')], default='casual', max_length=20)),
                ('image_style', models.CharField(choices=[('photographic', 'Photographic'), ('illustration', 'Illustration'), ('minimalist', 'Minimalist')], default='photographic', max_length=20)),
                ('wordpress_username', models.CharField(blank=True, max_length=100)),
                ('wordpress_app_password_encrypted', models.TextField(blank=True, null=True)),
                ('total_posts_generated', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
