# Generated by Django 5.2.10 on 2026-01-10 17:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContentSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('pt-BR', 'Português (Brasil)'), ('pt-PT', 'Português (Portugal)'), ('en-US', 'English (US)'), ('en-GB', 'English (UK)'), ('es-ES', 'Español (España)'), ('es-MX', 'Español (México)'), ('fr-FR', 'Français'), ('de-DE', 'Deutsch'), ('it-IT', 'Italiano')], default='pt-BR', help_text='Idioma principal do conteúdo gerado', max_length=10)),
                ('min_word_count', models.PositiveIntegerField(default=1200, help_text='Mínimo de palavras por artigo')),
                ('max_word_count', models.PositiveIntegerField(default=2000, help_text='Máximo de palavras por artigo')),
                ('h2_sections_min', models.PositiveIntegerField(default=5, help_text='Mínimo de seções H2')),
                ('h2_sections_max', models.PositiveIntegerField(default=8, help_text='Máximo de seções H2')),
                ('include_introduction', models.BooleanField(default=True, help_text='Incluir introdução engajante')),
                ('include_summary', models.BooleanField(default=False, help_text='Incluir resumo executivo no início')),
                ('include_faq', models.BooleanField(default=True, help_text='Incluir seção de perguntas frequentes')),
                ('faq_questions_count', models.PositiveIntegerField(default=5, help_text='Número de perguntas no FAQ')),
                ('include_conclusion', models.BooleanField(default=True, help_text='Incluir conclusão com CTA')),
                ('research_depth', models.CharField(choices=[('basic', 'Básico (3 fontes)'), ('standard', 'Padrão (5 fontes)'), ('deep', 'Profundo (10+ fontes)')], default='standard', help_text='Profundidade da pesquisa de dados', max_length=20)),
                ('research_recency_days', models.PositiveIntegerField(default=90, help_text='Considerar dados dos últimos X dias')),
                ('custom_writing_style', models.TextField(blank=True, help_text='Instruções de estilo (ex: "Use linguagem jovem, inclua emojis")')),
                ('custom_instructions', models.TextField(blank=True, help_text='Instruções adicionais para o gerador de conteúdo')),
                ('avoid_topics', models.TextField(blank=True, help_text='Tópicos a evitar, um por linha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_settings_obj', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Content Settings',
                'verbose_name_plural': 'Project Content Settings',
                'db_table': 'project_content_settings',
            },
        ),
    ]
