# Generated by Django 5.2.10 on 2026-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_project_content_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='research_model',
            field=models.CharField(default='perplexity/llama-3.1-sonar-large-128k-online', help_text='Modelo para pesquisa (ex: perplexity/sonar)', max_length=100),
        ),
    ]
