# Generated by Django 5.2.10 on 2026-01-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_research_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='research_model',
            field=models.CharField(default='perplexity/sonar', help_text='Modelo para pesquisa (ex: perplexity/sonar)', max_length=100),
        ),
    ]
