# Generated by Django 5.2.10 on 2026-01-12 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_research_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRSSSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed_url', models.URLField(blank=True, help_text='URL do feed RSS (ex: https://rss.app/feeds/xxx.xml)', max_length=1000)),
                ('is_active', models.BooleanField(default=False, help_text='Ativar monitoramento automático do feed')),
                ('check_interval_minutes', models.PositiveIntegerField(default=60, help_text='Intervalo entre verificações (minutos)')),
                ('auto_publish', models.BooleanField(default=False, help_text='Publicar automaticamente no WordPress')),
                ('max_posts_per_day', models.PositiveIntegerField(default=5, help_text='Limite máximo de posts por dia')),
                ('download_images', models.BooleanField(default=True, help_text='Baixar imagens do feed para Supabase')),
                ('include_source_attribution', models.BooleanField(default=True, help_text='Incluir atribuição à fonte original no post')),
                ('required_keywords', models.JSONField(blank=True, default=list, help_text='Palavras-chave obrigatórias (título ou descrição deve conter)')),
                ('blocked_keywords', models.JSONField(blank=True, default=list, help_text='Palavras-chave bloqueadas (ignorar itens que contenham)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('items_processed_today', models.PositiveIntegerField(default=0)),
                ('last_reset_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rss_settings', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project RSS Settings',
                'verbose_name_plural': 'Project RSS Settings',
                'db_table': 'project_rss_settings',
            },
        ),
    ]
