# Generated by Django 5.2.10 on 2026-01-12 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectrsssettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nome opcional para identificar o feed', max_length=255)),
                ('feed_url', models.URLField(help_text='URL do feed RSS (XML)', max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Projeto ao qual este feed pertence', on_delete=django.db.models.deletion.CASCADE, related_name='rss_feeds', to='projects.project')),
            ],
            options={
                'verbose_name': 'RSS Feed',
                'verbose_name_plural': 'RSS Feeds',
                'db_table': 'project_rss_feeds',
                'ordering': ['-created_at'],
            },
        ),
    ]
