# Generated by Django 5.2.10 on 2026-01-12 12:32

import uuid
from django.db import migrations, models


def generate_unique_magic_tokens(apps, schema_editor):
    """Generate unique UUID for each existing project."""
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all():
        project.magic_link_token = uuid.uuid4()
        project.save(update_fields=['magic_link_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rssfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access_sent_at',
            field=models.DateTimeField(blank=True, help_text='Último envio via WhatsApp', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='access_sent_count',
            field=models.IntegerField(default=0, help_text='Quantidade de envios'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_email',
            field=models.EmailField(blank=True, help_text='Email do cliente (opcional)', max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, help_text='Nome do responsável pelo projeto', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='client_phone',
            field=models.CharField(blank=True, help_text='WhatsApp do cliente (ex: 5519999999999)', max_length=20),
        ),
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name='project',
            name='magic_link_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token para acesso público', null=True),
        ),
        # Step 2: Generate unique UUIDs for existing records
        migrations.RunPython(generate_unique_magic_tokens, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='project',
            name='magic_link_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token para acesso público', unique=True),
        ),
    ]
