# Generated by Django 5.2.10 on 2026-01-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_add_plan_fields'),
        ('projects', '0007_project_access_sent_at_project_access_sent_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_plan',
            field=models.ForeignKey(blank=True, help_text='Plano do cliente para este projeto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='agencies.agencyclientplan'),
        ),
    ]
