version: '3.8'

services:
  web:
    image: postpro:latest
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - postpro_network

  worker:
    image: postpro:latest
    build: .
    command: celery -A config worker -l info --concurrency=2
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - postpro_network

  beat:
    image: postpro:latest
    build: .
    command: celery -A config beat -l info
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - postpro_network

  redis:
    image: redis:7-alpine
    expose:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - postpro_network

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  postpro_network:
    driver: overlay
