# Generated by Django 5.2.10 on 2026-01-08 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('max_projects', models.PositiveIntegerField(default=3)),
                ('monthly_posts_limit', models.PositiveIntegerField(default=100)),
                ('current_month_posts', models.PositiveIntegerField(default=0)),
                ('openrouter_api_key_encrypted', models.TextField(blank=True, null=True)),
                ('default_text_model', models.CharField(default='anthropic/claude-3.5-sonnet', max_length=100)),
                ('default_image_model', models.CharField(default='openai/gpt-4o-mini', max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('suspended', 'Suspended'), ('canceled', 'Canceled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'db_table': 'agencies',
                'ordering': ['-created_at'],
            },
        ),
    ]
