# Generated by Django 5.2.10 on 2026-01-10 18:13

import apps.agencies.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='branding_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nome exibido no painel. Se vazio, usa o campo 'name'", max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon (ICO ou PNG, 32x32px ou 64x64px)', null=True, upload_to=apps.agencies.models.agency_favicon_path, validators=[django.core.validators.FileExtensionValidator(['png', 'ico']), apps.agencies.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='agency',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Logo para tema escuro (PNG/SVG transparente, 200x50px recomendado)', null=True, upload_to=apps.agencies.models.agency_logo_dark_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp']), apps.agencies.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='agency',
            name='logo_light',
            field=models.ImageField(blank=True, help_text='Logo para tema claro (PNG/SVG transparente, 200x50px recomendado)', null=True, upload_to=apps.agencies.models.agency_logo_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg', 'webp']), apps.agencies.models.validate_image_size]),
        ),
        migrations.AddField(
            model_name='agency',
            name='primary_color',
            field=models.CharField(blank=True, default='#FF6B35', help_text='Cor primária em HEX (#FF6B35)', max_length=7),
        ),
        migrations.AddField(
            model_name='agency',
            name='secondary_color',
            field=models.CharField(blank=True, default='#004E89', help_text='Cor secundária em HEX', max_length=7),
        ),
        migrations.AlterField(
            model_name='agency',
            name='default_image_model',
            field=models.CharField(default='pollinations/flux', max_length=100),
        ),
    ]
