# Generated by Django 5.2.10 on 2026-01-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_branding_updated_at_agency_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='default_image_model',
            field=models.CharField(default='pollinations/flux', help_text='Modelo de imagem padrão para novos projetos', max_length=100),
        ),
        migrations.AlterField(
            model_name='agency',
            name='default_text_model',
            field=models.CharField(default='qwen/qwen3-32b', help_text='Modelo de texto padrão para novos projetos', max_length=100),
        ),
    ]
