# Generated by Django 5.2.10 on 2026-01-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_update_default_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='wuzapi_connected',
            field=models.BooleanField(default=False, help_text='Status da conexão'),
        ),
        migrations.AddField(
            model_name='agency',
            name='wuzapi_connected_at',
            field=models.DateTimeField(blank=True, help_text='Data/hora da última conexão', null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='wuzapi_instance_url',
            field=models.URLField(default='https://wuzapi.nuvemchat.com', help_text='URL da instância Wuzapi'),
        ),
        migrations.AddField(
            model_name='agency',
            name='wuzapi_phone',
            field=models.CharField(blank=True, help_text='Número WhatsApp conectado', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='wuzapi_token',
            field=models.CharField(blank=True, help_text='Token de autenticação', max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='wuzapi_user_id',
            field=models.IntegerField(blank=True, help_text='ID do usuário na Wuzapi', null=True),
        ),
    ]
