# Generated by Django 5.2.10 on 2026-01-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_agency_wuzapi_connected_agency_wuzapi_connected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='wuzapi_user_id',
            field=models.CharField(blank=True, help_text='ID do usuário na Wuzapi', max_length=100, null=True),
        ),
    ]
