# Generated by Django 5.2.10 on 2026-01-12 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_change_wuzapi_user_id_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wuzapi_instance_url', models.URLField(default='https://wuzapi.nuvemchat.com', help_text='URL da instância Wuzapi')),
                ('wuzapi_user_id', models.CharField(blank=True, help_text='ID do usuário na Wuzapi', max_length=100, null=True)),
                ('wuzapi_token', models.CharField(blank=True, help_text='Token de autenticação', max_length=255)),
                ('wuzapi_phone', models.CharField(blank=True, help_text='Número WhatsApp conectado', max_length=20)),
                ('wuzapi_connected', models.BooleanField(default=False, help_text='Status da conexão')),
                ('wuzapi_connected_at', models.DateTimeField(blank=True, help_text='Data/hora da última conexão', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Super Admin Config',
                'verbose_name_plural': 'Super Admin Configs',
                'db_table': 'superadmin_config',
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Email do responsável (opcional)', max_length=254),
        ),
        migrations.AddField(
            model_name='agency',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Nome do responsável pela agência', max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Telefone do responsável (usado para login e WhatsApp)', max_length=20),
        ),
        migrations.CreateModel(
            name='AgencyClientPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do plano (ex: Bronze, Prata, Ouro)', max_length=100)),
                ('posts_per_month', models.PositiveIntegerField(default=30, help_text='Limite de posts por mês para clientes deste plano')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Preço mensal (opcional)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_plans', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Agency Client Plan',
                'verbose_name_plural': 'Agency Client Plans',
                'db_table': 'agency_client_plans',
                'ordering': ['agency', 'posts_per_month'],
            },
        ),
    ]
