# Generated by Django 5.2.10 on 2026-01-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_add_agency_owner_fields_and_client_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agencyclientplan',
            options={'ordering': ['agency', 'order', 'posts_per_month'], 'verbose_name': 'Agency Client Plan', 'verbose_name_plural': 'Agency Client Plans'},
        ),
        migrations.AddField(
            model_name='agencyclientplan',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição detalhada do plano'),
        ),
        migrations.AddField(
            model_name='agencyclientplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='Lista de features, ex: ["10 posts", "Suporte 24h"]'),
        ),
        migrations.AddField(
            model_name='agencyclientplan',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Destaque visual na landing page (plano recomendado)'),
        ),
        migrations.AddField(
            model_name='agencyclientplan',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição (menor = primeiro)'),
        ),
    ]
