# Generated by Django 5.2.10 on 2026-01-13 01:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_add_plan_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyLandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hero_title', models.CharField(blank=True, help_text='Título principal do hero', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Subtítulo/descrição do hero')),
                ('about_section', models.TextField(blank=True, help_text="Texto da seção 'Sobre'")),
                ('cta_text', models.CharField(default='Começar Agora', help_text='Texto do botão CTA principal', max_length=100)),
                ('meta_title', models.CharField(blank=True, help_text='Título SEO (máx 60 caracteres)', max_length=60)),
                ('meta_description', models.CharField(blank=True, help_text='Descrição SEO (máx 160 caracteres)', max_length=160)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Número WhatsApp para contato (ex: 5511999999999)', max_length=20)),
                ('email_contact', models.EmailField(blank=True, help_text='Email para contato', max_length=254)),
                ('is_published', models.BooleanField(default=False, help_text='Landing page está publicada e acessível?')),
                ('ai_generated_at', models.DateTimeField(blank=True, help_text='Quando o conteúdo foi gerado pela IA', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landing_page', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Agency Landing Page',
                'verbose_name_plural': 'Agency Landing Pages',
                'db_table': 'agency_landing_pages',
            },
        ),
        migrations.CreateModel(
            name='AgencyLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, help_text='Nome da empresa/site do lead', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Mensagem opcional do lead')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('converted', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre o lead')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='agencies.agency')),
                ('plan', models.ForeignKey(blank=True, help_text='Plano de interesse selecionado pelo lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='agencies.agencyclientplan')),
            ],
            options={
                'verbose_name': 'Agency Lead',
                'verbose_name_plural': 'Agency Leads',
                'db_table': 'agency_leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
