# Generated by Django 5.2.10 on 2026-01-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_agency_landing_page_and_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencylandingpage',
            name='extended_content',
            field=models.JSONField(blank=True, default=dict, help_text='Conteúdo adicional gerado por IA (FAQ, benefits, pain points, etc)', verbose_name='Conteúdo Estendido'),
        ),
    ]
