# Generated by Django 5.2.10 on 2026-01-08 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='batch_uploads/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.JSONField(blank=True, default=dict)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_dry_run', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Batch Job',
                'verbose_name_plural': 'Batch Jobs',
                'db_table': 'batch_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('featured_image_url', models.URLField(blank=True, max_length=1000)),
                ('research_data', models.JSONField(blank=True, default=dict)),
                ('strategy_data', models.JSONField(blank=True, default=dict)),
                ('step_state', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('published', 'Published'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('wordpress_post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('wordpress_idempotency_key', models.CharField(blank=True, max_length=64, null=True)),
                ('wordpress_edit_url', models.URLField(blank=True, max_length=1000)),
                ('text_generation_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('image_generation_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('batch_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='automation.batchjob')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='projects.project')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('wordpress_publish', 'WordPress Publish'), ('post_generation', 'Post Generation'), ('batch_row', 'Batch Row')], max_length=30)),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('completed', 'Completed'), ('failed', 'Failed')], default='reserved', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='projects.project')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idempotency_keys', to='automation.post')),
            ],
            options={
                'verbose_name': 'Idempotency Key',
                'verbose_name_plural': 'Idempotency Keys',
                'db_table': 'idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='agencies.agency')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agency', '-created_at'], name='activity_lo_agency__bf4d14_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_78df1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PostArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step', models.CharField(choices=[('research', 'Research'), ('strategy', 'Strategy'), ('article', 'Article'), ('image', 'Image')], max_length=20)),
                ('input_prompt', models.TextField(blank=True)),
                ('system_prompt', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('parsed_output', models.JSONField(blank=True, default=dict)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='automation.post')),
            ],
            options={
                'verbose_name': 'Post Artifact',
                'verbose_name_plural': 'Post Artifacts',
                'db_table': 'post_artifacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'step', 'is_active'], name='post_artifa_post_id_9af527_idx')],
            },
        ),
    ]
