# Generated by Django 5.2.10 on 2026-01-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='wordpress_edit_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
