# Generated by Django 5.2.10 on 2026-01-09 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        ('automation', '0002_allow_null_wordpress_edit_url'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AIModelPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preset_category', models.CharField(blank=True, max_length=20)),
                ('planning_trends_model', models.CharField(default='perplexity/sonar', max_length=100)),
                ('planning_titles_model', models.CharField(default='mistralai/mistral-nemo', max_length=100)),
                ('outline_model', models.CharField(default='mistralai/mistral-nemo', max_length=100)),
                ('article_model', models.CharField(default='openai/gpt-oss-120b', max_length=100)),
                ('seo_model', models.CharField(default='openai/gpt-5-nano', max_length=100)),
                ('qa_model', models.CharField(default='openai/gpt-5-nano', max_length=100)),
                ('rewrite_model', models.CharField(blank=True, max_length=100)),
                ('max_search_requests_per_plan', models.PositiveIntegerField(default=3)),
                ('trends_recency_days', models.PositiveIntegerField(default=7)),
                ('image_provider', models.CharField(default='openrouter', max_length=20)),
                ('image_model_openrouter', models.CharField(blank=True, max_length=100)),
                ('pollinations_model', models.CharField(blank=True, max_length=100)),
                ('pollinations_width', models.PositiveIntegerField(default=1920)),
                ('pollinations_height', models.PositiveIntegerField(default=1080)),
                ('pollinations_safe', models.BooleanField(default=True)),
                ('pollinations_private', models.BooleanField(default=True)),
                ('pollinations_enhance', models.BooleanField(default=False)),
                ('pollinations_nologo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_policies', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'AI Model Policy',
                'verbose_name_plural': 'AI Model Policies',
                'db_table': 'ai_model_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_url', models.URLField(max_length=500)),
                ('site_name', models.CharField(max_length=255)),
                ('site_description', models.TextField(blank=True)),
                ('language', models.CharField(default='pt-BR', max_length=10)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('recent_posts', models.JSONField(blank=True, default=list)),
                ('main_pages', models.JSONField(blank=True, default=list)),
                ('sitemap_url', models.URLField(blank=True, max_length=500)),
                ('content_themes', models.JSONField(blank=True, default=list)),
                ('tone_analysis', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_profiles', to='projects.project')),
            ],
            options={
                'verbose_name': 'Site Profile',
                'verbose_name_plural': 'Site Profiles',
                'db_table': 'site_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', models.JSONField(default=list)),
                ('recency_days', models.PositiveIntegerField(default=7)),
                ('model_used', models.CharField(max_length=100)),
                ('insights', models.JSONField(default=list)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_packs', to='agencies.agency')),
            ],
            options={
                'verbose_name': 'Trend Pack',
                'verbose_name_plural': 'Trend Packs',
                'db_table': 'trend_packs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keywords', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='generating', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('posts_per_day', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorial_plans', to='projects.project')),
                ('site_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_plans', to='automation.siteprofile')),
                ('trend_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_plans', to='automation.trendpack')),
            ],
            options={
                'verbose_name': 'Editorial Plan',
                'verbose_name_plural': 'Editorial Plans',
                'db_table': 'editorial_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=500)),
                ('keyword_focus', models.CharField(max_length=200)),
                ('cluster', models.CharField(blank=True, max_length=100)),
                ('search_intent', models.CharField(blank=True, max_length=50)),
                ('trend_references', models.JSONField(blank=True, default=list)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='automation.editorialplan')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_plan_item', to='automation.post')),
            ],
            options={
                'verbose_name': 'Editorial Plan Item',
                'verbose_name_plural': 'Editorial Plan Items',
                'db_table': 'editorial_plan_items',
                'ordering': ['plan', 'day_index'],
                'indexes': [models.Index(fields=['plan', 'day_index'], name='editorial_p_plan_id_1a3234_idx'), models.Index(fields=['external_id'], name='editorial_p_externa_e4c36b_idx')],
            },
        ),
    ]
