# Generated by Django 5.2.10 on 2026-01-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_post_external_id_post_post_status_post_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialplan',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='generating', max_length=20),
        ),
    ]
