# Generated by Django 5.2.10 on 2026-01-12 01:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_alter_editorialplan_status'),
        ('projects', '0005_projectrsssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_type',
            field=models.CharField(choices=[('blog', 'Blog Post'), ('news', 'News Article')], default='blog', help_text='Tipo de artigo: Blog Post ou News Article', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='source_name',
            field=models.CharField(blank=True, help_text='Nome do portal de origem', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL da notícia original (para posts RSS)', max_length=1000),
        ),
        migrations.CreateModel(
            name='RSSItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(db_index=True, help_text='URL original da notícia', max_length=1000)),
                ('source_title', models.CharField(max_length=500)),
                ('source_description', models.TextField(blank=True)),
                ('source_image_url', models.URLField(blank=True, max_length=1000)),
                ('source_published_at', models.DateTimeField(blank=True, null=True)),
                ('source_author', models.CharField(blank=True, max_length=255)),
                ('source_hash', models.CharField(db_index=True, help_text='SHA256 hash for deduplication', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rss_source_items', to='automation.post')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rss_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'RSS Item',
                'verbose_name_plural': 'RSS Items',
                'db_table': 'rss_items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'source_hash'], name='rss_items_project_e356ee_idx'), models.Index(fields=['project', 'status'], name='rss_items_project_730a9b_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'source_url'), name='unique_rss_item_per_project')],
            },
        ),
    ]
